baseImages:
  alma-linux-10:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "10"
    digest: sha256:e901f9c9e24e599343a8c53c4fb45071aa73d1d2b0f0c406f771972de8481050
  alma-linux-rpi-10:
    image: quay.io/almalinuxorg/almalinux-bootc-rpi
    tag: "10"
    digest: sha256:4b05ea0c1a6a7d4748d693874fe304f27ca7e1fef75caa1b5b8f0c45344bd908
  centos-stream-10:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream10
    digest: sha256:fdb6387f6010182e117ed8a47e81a0663cee512573221bf6551d306e514e8440
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-k3s
  - server-k3s-zfs
  - server-worker
  - server-worker-zfs
  - server-atlas
  - server-boba
  - server-mochi
apps:
  - alloy
  - cloudflared
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
