baseImages:
  alma-linux-10:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "10"
    digest: sha256:55a2793612b208791c8c08b364629dbb5f836b314a91f1471c13465b4a84f230
  alma-linux-rpi-10:
    image: quay.io/almalinuxorg/almalinux-bootc-rpi
    tag: "10"
    digest: sha256:fe0bf55dc31b1b60de782d80cd92eef6de51932622bade281f8862fb7713fa75
  centos-stream-10:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream10
    digest: sha256:95397e8d1f672245159fdd4986130ec3999a91f3c6a5a788ce1d5ca28567e012
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-k3s
  - server-k3s-zfs
  - server-worker
  - server-worker-zfs
  - server-atlas
  - server-boba
  - server-mochi
apps:
  - alloy
  - cloudflared
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
