baseImages:
  alma-linux-10:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "10"
    digest: sha256:1395aa1fa45ab7b2dc915edcbe7237c1fd9a42a34e9f6a95cd8d9a99dcfef4c0
  alma-linux-rpi-10:
    image: quay.io/almalinuxorg/almalinux-bootc-rpi
    tag: "10"
    digest: sha256:9b7895ace9e14aa7ca77ea08dacc24781aebee3fc9fcc5f7734254b7a043f203
  centos-stream-10:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream10
    digest: sha256:99b3e11689c57e560da8398d6cd272814d9c95b3046a29961e017101a2e30409
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-k3s
  - server-k3s-zfs
  - server-worker
  - server-worker-zfs
  - server-atlas
  - server-boba
  - server-mochi
apps:
  - alloy
  - cloudflared
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
