name: tailscale
containerfile: Containerfile
version: 1.86.2
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/tailscale/tailscale/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
ignoredVersions:
  - 1.84.1
  - 1.84.2
