# Base image for the final layer
ARG BASE_IMAGE=quay.io/centos-bootc/centos-bootc:stream9

FROM ${BASE_IMAGE}

RUN <<EOT
  set -euxo pipefail

  # Add the EPEL repositories, jq and tmux
  dnf install -y \
    epel-release jq tmux

  # From the EPEL repositories, add:
  # screen, pv, sqlite
  dnf install -y --enablerepo=epel \
    screen pv sqlite

  # Add restic, fetching the RPM from the official GitHub repository
  # The RPM that is shipped in the official repositories is often very outdated
  ARCH=""
  case $(uname -m) in
    x86_64) ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
  esac
  # Get the latest release
  RESTIC_VERSION=$(curl -Ls "https://api.github.com/repos/restic/restic/releases/latest" | jq ".tag_name" -r)
  # Remove leading v
  RESTIC_VERSION=${RESTIC_VERSION:1}
  RESTIC_DOWNLOAD_URL=$(curl -sL https://api.github.com/repos/restic/restic/releases/latest | jq -r ".assets[] | select(.name == \"restic_${RESTIC_VERSION}_linux_${ARCH}.bz2\") | .browser_download_url")
  RESTIC_SHASUMS_URL=$(curl -sL https://api.github.com/repos/restic/restic/releases/latest | jq -r ".assets[] | select(.name == \"SHA256SUMS\") | .browser_download_url")
  # Download the binary
  curl -sLO "$RESTIC_DOWNLOAD_URL"
  curl -sLo restic-shasums "$RESTIC_SHASUMS_URL"
  cat restic-shasums | sha256sum --check --ignore-missing --status
  bunzip2 -c "restic_${RESTIC_VERSION}_linux_${ARCH}.bz2" > /usr/local/bin/restic
  chmod +x /usr/local/bin/restic
  /usr/local/bin/restic version

  # Add Tailscale
  dnf config-manager --add-repo https://pkgs.tailscale.com/stable/centos/9/tailscale.repo
  dnf install -y tailscale
  systemctl enable tailscaled

  # Add gotop, fetching the RPM from the official GitHub repository
  # This is installed on x86_64 only as pre-compiled RPMs are not available for other archs from the project
  if [ "$(uname -m)" = "x86_64" ]; then
    # Hardcoding these since gotop doesn't publish SHASUM files, and they haven't published a new release in a while
    GOTOP_VERSION="v4.2.0"
    GOTOP_SHA256SUM="9c3f2f072b82918c56a15a229b528ba7d1e01d54cc809f64555852fa775ef8a6"
    curl -Lo gotop.rpm "https://github.com/xxxserxxx/gotop/releases/download/${GOTOP_VERSION}/gotop_${GOTOP_VERSION}_linux_amd64.rpm"
    echo "${GOTOP_SHA256SUM} gotop.rpm" | sha256sum --check --status
    dnf install -y gotop.rpm
  fi

  # Clean-up
  dnf clean all
EOT
