ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ARG VERSION_TAILSCALE
ARG VERSION_RESTIC
ARG CHECKSUMS_RESTIC
ARG VERSION_GOTOP
ARG CHECKSUMS_GOTOP

RUN <<EOT
  set -euxo pipefail

  # Add the EPEL repositories
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  # Fix for certain scenarios where $releasever is incorrect with EPEL
  # See: https://bugzilla.redhat.com/show_bug.cgi?id=2219796
  sed -i 's/$releasever/9/g' /etc/yum.repos.d/epel*.repo

  # Add: screen, pv, sqlite, tmux, jq
  dnf install -y --enablerepo=epel \
    screen pv sqlite tmux jq

  # Add restic, fetching the RPM from the official GitHub repository
  # The RPM that is shipped in the official repositories is often very outdated
  ARCH=""
  case $(uname -m) in
    x86_64) ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
  esac

  # Download the binary
  curl -sLO "https://github.com/restic/restic/releases/download/v${VERSION_RESTIC}/restic_${VERSION_RESTIC}_linux_${ARCH}.bz2"
  echo "${CHECKSUMS_RESTIC}" | sha256sum --check --ignore-missing --status
  bunzip2 -c "restic_${VERSION_RESTIC}_linux_${ARCH}.bz2" > /usr/local/bin/restic
  chmod +x /usr/local/bin/restic
  /usr/local/bin/restic version

  # Add gotop, fetching the RPM from the official GitHub repository
  # This is installed on x86_64 only as pre-compiled RPMs are not available for other archs from the project
  if [ "$(uname -m)" = "x86_64" ]; then
    curl -LO "https://github.com/xxxserxxx/gotop/releases/download/v${VERSION_GOTOP}/gotop_v${VERSION_GOTOP}_linux_amd64.rpm"
    echo "${CHECKSUMS_GOTOP}" | sha256sum --check --ignore-missing --status
    dnf install -y "gotop_v${VERSION_GOTOP}_linux_amd64.rpm"
  fi

  # Clean-up
  dnf clean all
EOT
