ARG BASE_IMAGE

FROM ${BASE_IMAGE}

RUN <<EOT
  set -euxo pipefail

  # Add the EPEL repositories
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

  # Add: screen, pv, sqlite, tmux, jq, rsync, tree
  dnf install -y --enablerepo=epel \
    screen pv sqlite tmux jq rsync tree

  # Needed to get the right permissions on /run/screen on every boot
  cat <<'CONF' > /etc/tmpfiles.d/screen.conf
d /run/screen 0777 root root -
CONF

  # Clean-up
  dnf clean all
EOT
