ARG BASE_IMAGE

FROM ${BASE_IMAGE}

RUN <<EOT
  set -euxo pipefail

  # Add the EPEL repositories
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

  # Add: screen, pv, sqlite, tmux, jq, rsync, tree
  dnf install -y --enablerepo=epel \
    screen pv sqlite tmux jq rsync tree

  # Set permissions on /run/screen, required by screen
  chmod 0777 /run/screen

  # Clean-up
  dnf clean all
EOT
