name: yq
containerfile: Containerfile
version: 4.49.2
checksums: |-
  be2c0ddcf426b6a231648610ec5d1666ae50e9f6473e82f6486f9f4cb6e3e2f7 yq_linux_amd64
  783aa3c3beedcf2bf4aaf6262eca38b92a16d3ea31e2218ca80ba8ec7226b248 yq_linux_arm64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
