name: yq
containerfile: Containerfile
version: 4.45.3
checksums: |-
  2c621387e61e7f6bd14e85077c4bce36bc99d198804721501a1f14c236f3a2a9 yq_linux_amd64
  811092e109e53060bba9982ebdb4f79e60893a5a4f693aa6661309471fd39e67 yq_linux_arm64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
