name: yq
containerfile: Containerfile
version: 4.53.4
checksums: |-
  8c3cf4cff01536588947b6e0ba1544768039e34054cd9ca8a9e4c5706dfb8631 yq_linux_arm64
  f67d8a6a2dc2308c961f83d5ba8707fd4c7c44ad77902fef87eb3a4646cdfa2a yq_linux_amd64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
