name: yq
containerfile: Containerfile
version: 4.52.5
checksums: |-
  75d893a0d5940d1019cb7cdc60001d9e876623852c31cfc6267047bc31149fa9 yq_linux_amd64
  90fa510c50ee8ca75544dbfffed10c88ed59b36834df35916520cddc623d9aaa yq_linux_arm64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
