name: restic
version: 0.17.3
checksums: |-
  5097faeda6aa13167aae6e36efdba636637f8741fed89bbf015678334632d4d3  restic_0.17.3_linux_amd64.bz2
  db27b803534d301cef30577468cf61cb2e242165b8cd6d8cd6efd7001be2e557  restic_0.17.3_linux_arm64.bz2
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/restic/restic/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/restic/restic/releases/latest \
      | jq -r '.assets[] | select(.name == "SHA256SUMS") | .browser_download_url')
    curl -sL $URL \
      | grep "linux_arm64\|linux_amd64"
