name: restic
containerfile: Containerfile
version: 0.19.0
checksums: |-
  13176fe6d89d4357947a2cd107218ab2873a5f9d8e1ac2d4cd1c8e07e6839c21  restic_0.19.0_linux_amd64.bz2
  e522ce6bf748d753fee8093e8ec59359972cf5b6bc65fc7c7cf38ae952351d91  restic_0.19.0_linux_arm64.bz2
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/restic/restic/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/restic/restic/releases/latest \
      | jq -r '.assets[] | select(.name == "SHA256SUMS") | .browser_download_url')
    curl -sL $URL \
      | grep "linux_arm64\|linux_amd64"
