name: restic
containerfile: Containerfile
version: 0.18.0
checksums: |-
  98f6dd8bf5b59058d04bfd8dab58e196cc2a680666ccee90275a3b722374438e  restic_0.18.0_linux_amd64.bz2
  ce18179c25dc5f2e33e3c233ba1e580f9de1a4566d2977e8d9600210363ec209  restic_0.18.0_linux_arm64.bz2
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/restic/restic/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/restic/restic/releases/latest \
      | jq -r '.assets[] | select(.name == "SHA256SUMS") | .browser_download_url')
    curl -sL $URL \
      | grep "linux_arm64\|linux_amd64"
