baseImages:
  alma-linux-9:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "9"
    digest: sha256:1385489a455105fb2d149b477c08283c33cbf7a419cd63524d09c7e03f806f20
  centos-stream-9:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream9
    digest: sha256:eb4ee8ed4824fcf73c56af7b940c084e140e3827a384b9e090e12e2a4f107b8d
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-atlas
  - server-k3s
  - server-worker
apps:
  - alloy
  - cloudflared
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
