baseImages:
  alma-linux-9:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "9"
    digest: sha256:62b1120e4900930dc62b4076a84356ca7a96fbe4eaed77dd1d43a038e79866da
  centos-stream-9:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream9
    digest: sha256:6688001e1e35b3425d3c2a1045894e3111123a04f5a161658ca68c74fc537eae
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-atlas
  - server-k3s
  - server-worker
apps:
  - alloy
  - cloudflared
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
