baseImages:
  alma-linux-9:
    image: quay.io/almalinuxorg/almalinux-bootc
    tag: "9"
    digest: sha256:8273867d686102e78a78ad6edc4f136b724db15d7f4fda816c22bef8c7e19042
    architectures:
      - amd64
      - arm64
  centos-stream-9:
    image: quay.io/centos-bootc/centos-bootc
    tag: stream9
    digest: sha256:15ecf382074d6fcc590cba7ece1feedce479b249c55fc91a60905e0fb8cb56b4
    architectures:
      - amd64
      - arm64
folders:
  apps: apps
  containers: containers
containers:
  - base
  - tailscale
  - zfs
  - monitoring
  - monitoring-zfs
  - k3s
  - server
  - server-zfs
  - server-k3s
  - server-worker
apps:
  - alloy
  - gotop
  - k3s
  - restic
  - tailscale
  - yq
  - zfs
