name: zfs
containerfile: Containerfile
builderContainerfiles:
  - Containerfile-builder
version: 2.4.4
checksums: 2a3c70d55a37cc71618a95a60e81ad66530201eb118d37741dc92efcf848c8b1  zfs-2.4.4.tar.gz
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 5-
  updateChecksums: |
    VERSION=$(curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r)
    curl -sL "https://github.com/openzfs/zfs/releases/download/${VERSION}/${VERSION}.sha256.asc" \
      | grep ${VERSION}.tar.gz
