name: zfs
containerfile: Containerfile
builderContainerfiles:
  - Containerfile-builder
version: 2.4.3
checksums: 1f08f2d154f5189b5f1382848a32667b3d34066145b474c49cd3d41a5fba59a7  zfs-2.4.3.tar.gz
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 5-
  updateChecksums: |
    VERSION=$(curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r)
    curl -sL "https://github.com/openzfs/zfs/releases/download/${VERSION}/${VERSION}.sha256.asc" \
      | grep ${VERSION}.tar.gz
