COPY --from=builder-zfs /zfs/*.rpm /zfs/
RUN <<EOT
  set -euxo pipefail

  # ZFS
  # We install a bunch of RPMs, probably more than needed
  rm \
    /zfs/*devel*.rpm \
    /zfs/zfs-test*.rpm
  dnf install -y \
    /zfs/*.$(rpm -qa kernel --queryformat '%{ARCH}').rpm
  # Auto-load ZFS module
  depmod -a "$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')"
  echo "zfs" > /etc/modules-load.d/zfs.conf
  # We don't want any files on /var and /zfs
  rm -rf /var/lib/pcp /zfs

  # Add hdparm, sdparm, smartmontools
  dnf install -y hdparm sdparm smartmontools

  # Clean-up
  dnf clean all
EOT
