ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ARG VERSION_ALLOY

RUN <<EOT
  set -euxo pipefail

  # Grafana Alloy
  # https://grafana.com/docs/alloy/latest/set-up/install/linux/
  echo -e '[grafana]\nname=grafana\nbaseurl=https://rpm.grafana.com\nrepo_gpgcheck=1\nenabled=1\ngpgcheck=1\ngpgkey=https://rpm.grafana.com/gpg.key\nsslverify=1\nsslcacert=/etc/pki/tls/certs/ca-bundle.crt' | sudo tee /etc/yum.repos.d/grafana.repo
  dnf install -y alloy-${VERSION_ALLOY}

  # prometheus-podman-exporter
  dnf install -y prometheus-podman-exporter

  dnf clean all
EOT
