name: zfs
containerfile: Containerfile
builderContainerfiles:
  - Containerfile-builder
version: 2.4.1
checksums: c17b69770f0023154f578eb8c7536a70f07d6a3bb0bd38f04fa0e8811c3c1390  zfs-2.4.1.tar.gz
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 5-
  updateChecksums: |
    VERSION=$(curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r)
    curl -sL "https://github.com/openzfs/zfs/releases/download/${VERSION}/${VERSION}.sha256.asc" \
      | grep ${VERSION}.tar.gz
