name: zfs
containerfile: Containerfile
builderContainerfiles:
  - Containerfile-builder
version: 2.4.2
checksums: 7e260d0e6af295bea4c5e241cac0a1aef07b58d8dd8035f7898ade3b1bbec78f  zfs-2.4.2.tar.gz
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 5-
  updateChecksums: |
    VERSION=$(curl -Ls "https://api.github.com/repos/openzfs/zfs/releases/latest" \
      | jq '.tag_name' -r)
    curl -sL "https://github.com/openzfs/zfs/releases/download/${VERSION}/${VERSION}.sha256.asc" \
      | grep ${VERSION}.tar.gz
