# Base image for the final layer
ARG BASE_IMAGE=quay.io/centos-bootc/centos-bootc:stream9

FROM ${BASE_IMAGE}

ARG VERSION_TAILSCALE

# Add tailscaled
RUN <<EOT
  set -euxo pipefail

  # Get repo name for Tailscale
  REPO=""
  case $(grep -oP '(?<=^ID=).+' /etc/os-release | tr -d '"') in
    rhel) REPO="rhel/9" ;;
    centos) REPO="centos/9" ;;
    # Default to Fedora
    *) REPO="fedora" ;;
  esac

  dnf config-manager --add-repo "https://pkgs.tailscale.com/stable/${REPO}/tailscale.repo"
  dnf install -y tailscale-${VERSION_TAILSCALE}
  dnf clean all

  systemctl enable tailscaled
EOT