# Base image for the final layer
ARG BASE_IMAGE=quay.io/centos-bootc/centos-bootc:stream9

FROM ${BASE_IMAGE}

# Add tailscaled
RUN \
  dnf config-manager --add-repo https://pkgs.tailscale.com/stable/centos/9/tailscale.repo && \
  dnf install -y tailscale && \
  dnf clean all && \
  systemctl enable tailscaled
