name: yq
containerfile: Containerfile
version: 4.53.2
checksums: |-
  d56bf5c6819e8e696340c312bd70f849dc1678a7cda9c2ad63eebd906371d56b yq_linux_amd64
  03061b2a50c7a498de2bbb92d7cb078ce433011f085a4994117c2726be4106ea yq_linux_arm64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
