name: yq
containerfile: Containerfile
version: 4.49.1
checksums: |-
  897045e4a42933951ea8e143c44ea3f7f8005aa25105c4fbd796c3d61ee163ec yq_linux_amd64
  48e09de3f65cb5de1cdf7ae9ba78676f147be376db2727be5dca8213aa898012 yq_linux_arm64
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/mikefarah/yq/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |-
    URL=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest \
      | jq -r '.assets[] | select(.name == "checksums") | .browser_download_url')
    # See: https://github.com/mikefarah/yq/blob/master/scripts/extract-checksum.sh
    curl -sL $URL \
      | grep "yq_linux_amd64 \|yq_linux_arm64 " \
      | sed 's/  /\t/g' \
      | cut -f1,19 \
      | awk '{ print $2 " " $1}'
