# Base image for the final layer
ARG BASE_IMAGE=quay.io/centos-bootc/centos-bootc:stream9

# Using https://openzfs.github.io/openzfs-docs/Developer%20Resources/Custom%20Packages.html
FROM ${BASE_IMAGE} AS builder

# We can't use `uname -r` as it will pick up the host kernel version
RUN \
  rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' \
    | tee /kernel-version.txt

# Install build depdendencies
RUN \
  dnf install -y \
    jq epel-release make autoconf automake gcc libtool rpm-build libblkid-devel \
    libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel libattr-devel elfutils-libelf-devel \
    kernel-$(cat /kernel-version.txt) kernel-modules-$(cat /kernel-version.txt) kernel-devel-$(cat /kernel-version.txt) \
    python3 python3-devel python3-setuptools python3-packaging python3-cffi libffi-devel git libcurl-devel
RUN \
  dnf install -y --enablerepo=epel --enablerepo=crb \
    dkms libtirpc-devel ncompress

WORKDIR /
RUN <<EOT
  set -euxo pipefail

  # Fetch latest version
  # Uses project_id from: https://release-monitoring.org/project/11706/
  curl "https://release-monitoring.org/api/v2/versions/?project_id=11706" \
    | jq -r '.stable_versions[0]' \
    | tee /zfs_version.txt

  curl -L -O https://github.com/openzfs/zfs/releases/download/zfs-$(cat /zfs_version.txt)/zfs-$(cat /zfs_version.txt).tar.gz
  tar xzf zfs-$(cat /zfs_version.txt).tar.gz
  mv zfs-$(cat /zfs_version.txt) zfs

  cd /zfs
  ./configure -with-linux=/usr/src/kernels/$(cat /kernel-version.txt)/ -with-linux-obj=/usr/src/kernels/$(cat /kernel-version.txt)/
  make -j1 rpm-utils rpm-kmod
  ls -al /zfs/*.rpm
EOT

# Final layer
FROM ${BASE_IMAGE}

COPY --from=builder /zfs/*.rpm /zfs/
RUN <<EOT
  set -euxo pipefail

  # ZFS
  # We install a bunch of RPMs, probably more than needed
  rm \
    /zfs/*devel*.rpm \
    /zfs/zfs-test*.rpm
  dnf install -y \
    /zfs/*.$(rpm -qa kernel --queryformat '%{ARCH}').rpm
  # Auto-load ZFS module
  depmod -a "$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')"
  echo "zfs" > /etc/modules-load.d/zfs.conf
  # We don't want any files on /var and /zfs
  rm -rf /var/lib/pcp /zfs

  # Add hdparm and smartmontools
  dnf install -y hdparm smartmontools

  # Clean-up
  dnf clean all
EOT
