name: cloudflared
containerfile: Containerfile
version: 2026.5.2
checksums: |-
  1207464355b914b5d0fb6db38c8616f9dc766d51e9c61ed1934b8814e57579c2  cloudflared-linux-aarch64.rpm
  4e808fbb537ec1d5e6caaadc44663a4b66aec2a500fc7368228960235be12628  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
