name: cloudflared
containerfile: Containerfile
version: 2025.10.0
checksums: |-
  ead1b5b3a21bcb6ac2f1ac396a995bd9658c08d311ad75d04d77fdba8d3ed0ce  cloudflared-linux-aarch64.rpm
  eb36510de1265067c72e67448688758707b7cc5d3524f1ce70cbd71ebfb530ee  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
