name: cloudflared
containerfile: Containerfile
version: 2026.1.2
checksums: |-
  dbdf6eed4e6b5f0c0f6311da77e34d0457d63d0aa558e9ede9462167de40c129  cloudflared-linux-aarch64.rpm
  e0289e640172c231ff5038828e394a7ac0c4b1050ff9399d380a9eedaf045afd  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
