name: cloudflared
containerfile: Containerfile
version: 2026.5.1
checksums: |-
  30d02e78f1f1bb713ef0df0b412b1289788a5204f98b42206e51349f9e26229a  cloudflared-linux-aarch64.rpm
  66b56510509f310a96462bad26d2a524e709687c2695ae65909696aead414815  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
