name: cloudflared
containerfile: Containerfile
version: 2025.9.1
checksums: |-
  e8c2a39d79c43e6333509e19a2221c7773bf99041d72f84ec511cc5bf55909ea  cloudflared-linux-aarch64.rpm
  37a6048cb484f1e14943246991f0cd12d4d33d6d4286ef1243a912ee26a4b118  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
