name: cloudflared
containerfile: Containerfile
version: 2025.11.1
checksums: |-
  c16538f5559005fd40c0f17990d35aa75ac6f68740bc5df58780788c5014b5d9  cloudflared-linux-aarch64.rpm
  3a9869680c08f8c29fb85736a9d44dfe9cd2b3aaec624955b3a1f39fbe2175b4  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
