name: cloudflared
containerfile: Containerfile
version: 2025.9.0
checksums: |-
  11360d94dbc89728557bbcca7c8475f7ca57f96df907da83921b68c10ee95dc9  cloudflared-linux-aarch64.rpm
  4a9a7efb6df006a40eaebecb6aa5e2cd4c4c4908b2acd895cf14271f9afca508  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
