name: cloudflared
containerfile: Containerfile
version: 2026.3.0
checksums: |-
  78e8394502900cf9312f094a2fabcc82c6594e9eb8459c51f6d5e1b1eb7ef7f3  cloudflared-linux-aarch64.rpm
  e1e717479e8b8db877b48788875657cbf3558e6cca2b69ab65004517181468c3  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
