name: cloudflared
containerfile: Containerfile
version: 2025.11.0
checksums: |-
  9074b62ae79a269ad01f65861919765ebbf31dd0f201b64fbe2fe03701df656d  cloudflared-linux-aarch64.rpm
  a4829cb80dd3ddcfceaebb3dd3db7406d588e990ecba8f8bad338b053e9121c9  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
