name: alloy
containerfile: Containerfile
version: 1.11.2
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/grafana/alloy/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
ignoredVersions:
  - 1.10.1
