name: alloy
containerfile: Containerfile
version: 1.8.3
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/grafana/alloy/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
