name: cloudflared
containerfile: Containerfile
version: 2026.7.2
checksums: |-
  90667866ad18c502ba6921b8db58645dc8a29ea3290f3fbdba1d30d82d6d2f4d  cloudflared-linux-aarch64.rpm
  243ae0f3e25225b322fca700ac45be53fe3f6821f9a43a944a36cd9e9f9895ad  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
