name: cloudflared
containerfile: Containerfile
version: 2026.9.3
checksums: |-
  e37b746dd252ab51b8dbe90f07eaf50c0335d137009cc224a97203acf1c331ab  cloudflared-linux-aarch64.rpm
  b64f9131b5ea2772c4a8fb9fb67f95437190ad63e909871396adb92c2b6d99eb  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
