name: cloudflared
containerfile: Containerfile
version: 2026.7.1
checksums: |-
  53a59e6c15f07c253ea9719e6bfd8ce0b64e98335d422f16185e762e4cfb809b  cloudflared-linux-aarch64.rpm
  0bf0252e7eef2275217e54ebd636db5e94059a3975e4dddcea2bc70cec26629c  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
