name: cloudflared
containerfile: Containerfile
version: 2026.2.0
checksums: |-
  b7078d84d73862227fc14b3aa4ca8e34c31b29879d8ae43eb7918f32e03676cb  cloudflared-linux-aarch64.rpm
  76753e8e0428df4f48f77109c1407fcad53e7fa5325049a1b5cc2293dc08c6f1  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
