name: cloudflared
containerfile: Containerfile
version: 2025.7.0
checksums: |-
  0b6a7a805d47203c50a7744ccac48285360c97f6eaf625fcd2c0c08f6b20472f  cloudflared-linux-aarch64.rpm
  69901a2636f61e1975f824b78e95ae14d2d1849f953d46dd2915c72241ff03ef  cloudflared-linux-x86_64.rpm
cmds:
  updateVersion: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.tag_name' -r
  updateChecksums: |
    curl -Ls "https://api.github.com/repos/cloudflare/cloudflared/releases/latest" \
      | jq '.body' -r \
      | tr -d '\r' \
      | grep "cloudflared-linux-x86_64.rpm\|cloudflared-linux-aarch64.rpm" \
      | awk -F': ' '{print $2 "  " $1}'
