name: k3s
containerfile: Containerfile
version: 1.36.2+k3s1
checksums: |-
  65a55ec56c24eab44383086166ec620a491952b7e23941a49ddca6e8a4c4b4de  k3s
  1dc5fc17f15c28fa0a3f011cee28ad613f918c3d967a426e5a05d43ddb239817  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
