name: k3s
containerfile: Containerfile
version: 1.36.4+k3s1
checksums: |-
  835873f37245fc615f547a2fe2af9402a347875f13fa64a1f136de644955ea3f  k3s
  c920706346d5ad4e5cd3c7bf1bb09ce71ebe07fec829e513e40f1caf98aed8bb  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
