name: k3s
containerfile: Containerfile
version: 1.36.0+k3s1
checksums: |-
  efa953454c8f7bf8d9d35c2dad2a76c9bdaac6860d60361629a3a2719009876b  k3s
  5a4e4e76ddacb7997384746992439b9a75ed930d8d2b9caf1938571d416d8a0e  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
