name: k3s
containerfile: Containerfile
version: 1.32.0+k3s1
checksums: |-
  c8b43f1e3e42d39386da625125bf2820f897ba068e86d7104ef06441240aaf52  k3s
  4b8ae2b8160e66cca858e9ee9ffa70c4e2fed5eb40e0b15e04490823acbaf3b4  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
