name: k3s
containerfile: Containerfile
version: 1.35.4+k3s1
checksums: |-
  080498ece50acdaf23fe5d736f41c616e276a89a4e5605a3f274f39b0fcee85b  k3s
  53eab87ef5601265a6cbd09756840646693e71db84ee8578884d8f7749345a73  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
