name: k3s
containerfile: Containerfile
version: 1.36.1+k3s1
checksums: |-
  a443db3fe9820cd93617ae67e4386d87c1514c1e96ceb30f4c2791c39065653c  k3s
  2240e9f7fd8cf36e9998d7ef18781975780d724b59408174618ec15b410891dc  k3s-arm64
cmds:
  updateVersion: |
    curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
      | jq '.tag_name' -r \
      | cut -c 2-
  updateChecksums: |
    VERSION=$(curl -sL "https://api.github.com/repos/k3s-io/k3s/releases/latest" | jq -r '.tag_name')
    # Print checksum for "k3s" (for amd64)
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-amd64.txt" | grep "k3s$"
    # Print checksum for "k3s-arm64"
    curl -sL "https://github.com/k3s-io/k3s/releases/download/${VERSION}/sha256sum-arm64.txt" | grep "k3s-arm64$"
